name: Controller YML

on: [ push, pull_request ]

jobs:
  #  controller1:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: ./.github/workflows/librarya.yml

  #  controller2:
  #    uses: ./.github/workflows/libraryb.yml

  lib-a-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: goodbye A ...
        shell: bash
        run: |
          git fetch origin master
          git diff --name-only origin/master...HEAD > file.txt
          chmod +x .github/scripts/goodbye.sh
          ./.github/scripts/goodbye.sh


  trigger-lib-z-workflow:
    needs: [ lib-a-check ]
    runs-on: ubuntu-latest
    steps:
      - name: goodbye Z ...
        shell: bash
        run: |
          cat file.txt
          rm file.txt
#    uses: ./.github/workflows/librarya.yml

  trigger-lib-a-workflow:
    needs: [ lib-a-check ]
    if: |
      github.event_name == 'nothing'
    uses: ./.github/workflows/librarya.yml

  trigger-lib-b-workflow:
    needs: [ lib-a-check ]
    if: |
      github.event_name == 'nothing'
    uses: ./.github/workflows/librarya.yml

  trigger-lib-c-workflow:
    needs: [ lib-a-check ]
    if: |
      github.event_name == 'nothing'
    uses: ./.github/workflows/librarya.yml

  trigger-lib-d-workflow:
    needs: [ lib-a-check ]
    if: |
      github.event_name == 'nothing'
    uses: ./.github/workflows/librarya.yml

#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 20
#
#      - name: goodbye B ...
#        shell: bash
#        run: |
#          git fetch origin master
#          git diff --name-only origin/master...HEAD
#
#          chmod +x .github/scripts/goodbye.sh
#          ./.github/scripts/goodbye.sh
#
#      - name: run-lib-b
#        uses: ./.github/workflows/libraryb.yml

#          echo "mydiff = "
#          cat mydiff
#          git diff --name-only origin/master...${{ github.head_commit.id }} | sort -u
#          sh ./.github/scripts/goodbye.sh
