name: Controller YML

on: [ push, pull_request ]

jobs:
#  controller1:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/workflows/librarya.yml

#  controller2:
#    uses: ./.github/workflows/libraryb.yml

  runshell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goodbye...
        shell: bash
        run: |
          git fetch origin master
          git diff origin/master...HEAD
#          echo "mydiff = "
#          cat mydiff
#          git diff --name-only origin/master...${{ github.head_commit.id }} | sort -u
#          sh ./.github/scripts/goodbye.sh
