
name: Library One Work Flow

on:
  push:
    branches:
      - master
      - master2
    paths:
      - 'libraryone/src/main/**'

  pull_request:
    branches:
      - master
      - master2
    paths:
      - 'libraryone/src/main/**'

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"
