
name: Library One Work Flow

# Controls when the workflow will run
on:
  push:
    paths:
      - 'libraryone/src/main/**'

  pull_request:
    branches: [ master ]
    paths:
      - 'libraryone/src/main/**'

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"
