# This is a basic workflow to help you get started with Actions

name: Library Two Work Flow

on:
  push:
    branches:
      - master
      - master2
      - '!norun/**'
    paths:
      - 'librarytwo/src/main/**'

  pull_request:
    branches:
      - master
      - master2
    paths:
      - 'librarytwo/src/main/**'
    types: [ labeled, opened, reopened, synchronize ]

  workflow_dispatch:

jobs:

  build-library-two:
    if: |
      contains(github.event.pull_request.labels.*.name, 'HELLO WORLD') ||
      github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
