name: Library D Pushed Work Flow

on:
  push:
    paths:
      - 'libraryd/src/main/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || '' }}
  cancel-in-progress: true

jobs:

  build-library-two:
    runs-on: ubuntu-latest

    #    if: |
    #      github.event_name == 'push' ||
    #      contains(github.event.pull_request.labels.*.name, 'HELLO WORLD')
    if: |
      github.event.pull_request.draft == false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $(date)
          echo $(date)
          sleep 30
          echo $(date)
