# This is a basic workflow to help you get started with Actions

name: Library Two Work Flow

on:
  push:
    branches:
      - master
      - master2
    paths:
      - 'librarytwo/src/main/**'

  pull_request:
    branches:
      - master
      - master2
    paths:
      - 'librarytwo/src/main/**'
    types:
      - ready_for_review
      - synchronize
#    types:
#      - labeled
#      - opened
#      - reopened
#      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || '' }}
  cancel-in-progress: true

jobs:

  build-library-two:
    runs-on: ubuntu-latest

#    if: |
#      github.event_name == 'push' ||
#      contains(github.event.pull_request.labels.*.name, 'HELLO WORLD')
    if: |
      github.event.pull_request.draft == false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $(date)
          echo $(date)
          sleep 30
          echo $(date)
