
name: Library One Work Flow

on:
  push:
    branches:
      - master
      - master2
    paths:
      - 'libraryone/src/main/**'

  pull_request:
    branches:
      - master
      - master2
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - 'libraryone/src/main/**'

  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-library-one:    
    if: |
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'HELLO WORLD')

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo | date
          echo | date
          sleep 15
          echo | date
