
name: Library One Requires Label Work Flow

on:
  push:
    branches:
      - master
      - master2
    paths:
      - 'libraryone/src/main/**'

  pull_request:
    branches:
      - master
      - master2
    paths:
      - 'libraryone/src/main/**'
    types: [ labeled ]

  workflow_dispatch:

jobs:
  build:
    if: ${{ (contains(github.event.pull_request.labels.*.name, 'HELLO WORLD') }}
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
