name: Library A Pushed Work Flow

on:
  push:
    paths:
      - 'librarya/src/main/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || '' }}
  cancel-in-progress: true

jobs:

  build-library-one:
#    if: |
#      github.event_name == 'push' ||
#      contains(github.event.pull_request.labels.*.name, 'HELLO WORLD')

    if: |
      github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $(date)
          echo $(date)
          sleep 30
          echo $(date)
