# This is a basic workflow to help you get started with Actions

name: App Work Flow

on:
  push:
    branches: [ master, master2 ]

  pull_request:
    branches: [ master, master2 ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
