# This is a basic workflow to help you get started with Actions
# This is a basic workflow to help you get started with Actions
# This is a basic workflow to help you get started with Actions

name: App Work Flow

on:
  push:
    branches:
      - master
      - master2

  pull_request:
    branches:
      - master
      - master2
    types:
      - review_requested
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || '' }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "==>"
          echo "$GITHUB_CONTEXT"
          echo $(date)
          echo $(date)
          sleep 30
          echo $(date)
